var a=10
var b=5
var nombre="Daniel"
console.log("mi primer projecto de consola")
console.log(nombre)
var mathad1=a+b
var mathmul1=a*b
var mathdiv1=a/b
var mathres1=a-b
var mathad2=b+a
var mathdiv2=b/a
var mathmul2=b*a
var mathres2=b-a
console.log(mathad1)
console.log(mathad2)
console.log(mathdiv1)
console.log(mathdiv2)
console.log(mathres1)
console.log(mathres2)
console.log(mathmul1)
console.log(mathmul2)

